export const SYSTEM_ROLES = {
  SYS_ADMIN: "SYS_ADMIN",
  ADMIN: "ADMIN",
  SUPERVISOR: "SUPERVISOR",
  FACULTY: "FACULTY",
  STUDENT: "STUDENT",
} as const;

export type RoleName = (typeof SYSTEM_ROLES)[keyof typeof SYSTEM_ROLES];

export const PERMISSIONS = {
  // Institutional records
  COLLEGE_CREATE: "college:create",
  COLLEGE_READ: "college:read",
  COLLEGE_UPDATE: "college:update",
  COLLEGE_DELETE: "college:delete",

  PROGRAM_CREATE: "program:create",
  PROGRAM_READ: "program:read",
  PROGRAM_UPDATE: "program:update",
  PROGRAM_DELETE: "program:delete",

  COURSE_CREATE: "course:create",
  COURSE_READ: "course:read",
  COURSE_UPDATE: "course:update",
  COURSE_DELETE: "course:delete",

  COURSE_CURRICULUM_CREATE: "course-curriculum:create",
  COURSE_CURRICULUM_READ: "course-curriculum:read",
  COURSE_CURRICULUM_UPDATE: "course-curriculum:update",
  COURSE_CURRICULUM_DELETE: "course-curriculum:delete",

  SEMESTER_CREATE: "semester:create",
  SEMESTER_READ: "semester:read",
  SEMESTER_UPDATE: "semester:update",
  SEMESTER_DELETE: "semester:delete",

  COURSE_OFFERING_CREATE: "course-offering:create",
  COURSE_OFFERING_READ: "course-offering:read",
  COURSE_OFFERING_UPDATE: "course-offering:update",
  COURSE_OFFERING_DELETE: "course-offering:delete",

  CLASS_CREATE: "class:create",
  CLASS_READ: "class:read",
  CLASS_UPDATE: "class:update",
  CLASS_DELETE: "class:delete",

  FACULTY_CREATE: "faculty:create",
  FACULTY_READ: "faculty:read",
  FACULTY_UPDATE: "faculty:update",
  FACULTY_DELETE: "faculty:delete",

  STUDENT_CREATE: "student:create",
  STUDENT_READ: "student:read",
  STUDENT_UPDATE: "student:update",
  STUDENT_DELETE: "student:delete",

  CLASS_STUDENT_CREATE: "class-student:create",
  CLASS_STUDENT_READ: "class-student:read",
  CLASS_STUDENT_DELETE: "class-student:delete",

  STUDENT_CLASS_CREATE: "student-class:create",
  STUDENT_CLASS_READ: "student-class:read",
  STUDENT_CLASS_DELETE: "student-class:delete",

  BULK_IMPORT_EXECUTE: "bulk-import:execute",

  // Evaluation configuration
  EVALUATION_PERIOD_MANAGE: "evaluation-period:manage",
  EVALUATION_FORM_MANAGE: "evaluation-form:manage",

  // Evaluation submission (the actual SET / SEF instruments)
  EVALUATION_SUBMIT_SET: "evaluation:submit-set",
  EVALUATION_SUBMIT_SEF: "evaluation:submit-sef",

  // Evaluation results
  EVALUATION_VIEW_OWN_RESULTS: "evaluation:view-own-results", // faculty viewing their own IFER
  EVALUATION_VIEW_ALL_RESULTS: "evaluation:view-all-results", // admin / supervisor

  REPORT_GENERATE_IFER: "report:generate-ifer",
  REPORT_GENERATE_FEDAF: "report:generate-fedaf",

  ACCOUNT_CREATE: "account:create",
  ACCOUNT_UPDATE: "account:update",
  ACCOUNT_DELETE: "account:delete",
  ACCOUNT_UPDATE_OWN: "account:update-own",
  ACCOUNT_MANAGE_ROLES: "account:manage-roles",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ROLE_PERMISSION_MATRIX: Record<RoleName, Permission[]> = {
  [SYSTEM_ROLES.SYS_ADMIN]: Object.values(PERMISSIONS),

  [SYSTEM_ROLES.ADMIN]: [
    PERMISSIONS.COLLEGE_CREATE,
    PERMISSIONS.COLLEGE_READ,
    PERMISSIONS.COLLEGE_UPDATE,
    PERMISSIONS.COLLEGE_DELETE,
    PERMISSIONS.PROGRAM_CREATE,
    PERMISSIONS.PROGRAM_READ,
    PERMISSIONS.PROGRAM_UPDATE,
    PERMISSIONS.PROGRAM_DELETE,
    PERMISSIONS.COURSE_CREATE,
    PERMISSIONS.COURSE_READ,
    PERMISSIONS.COURSE_UPDATE,
    PERMISSIONS.COURSE_DELETE,
    PERMISSIONS.COURSE_CURRICULUM_CREATE,
    PERMISSIONS.COURSE_CURRICULUM_READ,
    PERMISSIONS.COURSE_CURRICULUM_UPDATE,
    PERMISSIONS.COURSE_CURRICULUM_DELETE,
    PERMISSIONS.SEMESTER_CREATE,
    PERMISSIONS.SEMESTER_READ,
    PERMISSIONS.SEMESTER_UPDATE,
    PERMISSIONS.SEMESTER_DELETE,
    PERMISSIONS.COURSE_OFFERING_CREATE,
    PERMISSIONS.COURSE_OFFERING_READ,
    PERMISSIONS.COURSE_OFFERING_UPDATE,
    PERMISSIONS.COURSE_OFFERING_DELETE,
    PERMISSIONS.CLASS_CREATE,
    PERMISSIONS.CLASS_READ,
    PERMISSIONS.CLASS_UPDATE,
    PERMISSIONS.CLASS_DELETE,
    PERMISSIONS.FACULTY_CREATE,
    PERMISSIONS.FACULTY_READ,
    PERMISSIONS.FACULTY_UPDATE,
    PERMISSIONS.FACULTY_DELETE,
    PERMISSIONS.STUDENT_CREATE,
    PERMISSIONS.STUDENT_READ,
    PERMISSIONS.STUDENT_UPDATE,
    PERMISSIONS.STUDENT_DELETE,
    PERMISSIONS.CLASS_STUDENT_CREATE,
    PERMISSIONS.CLASS_STUDENT_READ,
    PERMISSIONS.CLASS_STUDENT_DELETE,
    PERMISSIONS.STUDENT_CLASS_CREATE,
    PERMISSIONS.STUDENT_CLASS_READ,
    PERMISSIONS.STUDENT_CLASS_DELETE,
    PERMISSIONS.BULK_IMPORT_EXECUTE,
    PERMISSIONS.EVALUATION_PERIOD_MANAGE,
    PERMISSIONS.EVALUATION_FORM_MANAGE,
    PERMISSIONS.EVALUATION_VIEW_ALL_RESULTS,
    PERMISSIONS.REPORT_GENERATE_IFER,
    PERMISSIONS.REPORT_GENERATE_FEDAF,
    PERMISSIONS.ACCOUNT_CREATE,
    PERMISSIONS.ACCOUNT_UPDATE,
    PERMISSIONS.ACCOUNT_DELETE,
    PERMISSIONS.ACCOUNT_UPDATE_OWN,
    PERMISSIONS.ACCOUNT_MANAGE_ROLES,
  ],

  [SYSTEM_ROLES.SUPERVISOR]: [
    PERMISSIONS.PROGRAM_READ,
    PERMISSIONS.COURSE_READ,
    PERMISSIONS.COURSE_CURRICULUM_READ,
    PERMISSIONS.SEMESTER_READ,
    PERMISSIONS.CLASS_READ,
    PERMISSIONS.FACULTY_READ,
    PERMISSIONS.STUDENT_READ,
    PERMISSIONS.CLASS_STUDENT_READ,
    PERMISSIONS.STUDENT_CLASS_READ,
    PERMISSIONS.EVALUATION_SUBMIT_SEF,
    PERMISSIONS.EVALUATION_VIEW_ALL_RESULTS,
    PERMISSIONS.REPORT_GENERATE_IFER,
    PERMISSIONS.REPORT_GENERATE_FEDAF,
    PERMISSIONS.ACCOUNT_UPDATE_OWN,
  ],

  [SYSTEM_ROLES.FACULTY]: [
    PERMISSIONS.CLASS_READ,
    PERMISSIONS.CLASS_STUDENT_READ, // see who's in their class
    PERMISSIONS.STUDENT_CLASS_READ, // see offerings per student
    PERMISSIONS.EVALUATION_VIEW_OWN_RESULTS,
    PERMISSIONS.ACCOUNT_UPDATE_OWN,
  ],

  [SYSTEM_ROLES.STUDENT]: [
    PERMISSIONS.CLASS_READ,
    PERMISSIONS.CLASS_STUDENT_READ, // see classmates (optional — remove if privacy concern)
    PERMISSIONS.STUDENT_CLASS_READ, // see own enrolled offerings
    PERMISSIONS.EVALUATION_SUBMIT_SET,
    PERMISSIONS.ACCOUNT_UPDATE_OWN,
  ],
};
