export const SYSTEM_ROLES = {
  SYS_ADMIN: "SYS_ADMIN",
  ADMIN: "ADMIN",
  SUPERVISOR: "SUPERVISOR",
  FACULTY: "FACULTY",
  STUDENT: "STUDENT",
} as const;

export type RoleName = (typeof SYSTEM_ROLES)[keyof typeof SYSTEM_ROLES];

export const PERMISSIONS = {
  // Institutional records
  COLLEGE_CREATE: "college:create",
  COLLEGE_READ: "college:read",
  COLLEGE_UPDATE: "college:update",
  COLLEGE_DELETE: "college:delete",

  PROGRAM_CREATE: "program:create",
  PROGRAM_READ: "program:read",
  PROGRAM_UPDATE: "program:update",
  PROGRAM_DELETE: "program:delete",

  COURSE_CREATE: "course:create",
  COURSE_READ: "course:read",
  COURSE_UPDATE: "course:update",
  COURSE_DELETE: "course:delete",

  COURSE_CURRICULUM_CREATE: "course-curriculum:create",
  COURSE_CURRICULUM_READ: "course-curriculum:read",
  COURSE_CURRICULUM_UPDATE: "course-curriculum:update",
  COURSE_CURRICULUM_DELETE: "course-curriculum:delete",

  SEMESTER_CREATE: "semester:create",
  SEMESTER_READ: "semester:read",
  SEMESTER_UPDATE: "semester:update",
  SEMESTER_DELETE: "semester:delete",

  COURSE_OFFERING_CREATE: "course-offering:create",
  COURSE_OFFERING_READ: "course-offering:read",
  COURSE_OFFERING_UPDATE: "course-offering:update",
  COURSE_OFFERING_DELETE: "course-offering:delete",

  CLASS_CREATE: "class:create",
  CLASS_READ: "class:read",
  CLASS_UPDATE: "class:update",
  CLASS_DELETE: "class:delete",

  FACULTY_CREATE: "faculty:create",
  FACULTY_READ: "faculty:read",
  FACULTY_UPDATE: "faculty:update",
  FACULTY_DELETE: "faculty:delete",

  STUDENT_CREATE: "student:create",
  STUDENT_READ: "student:read",
  STUDENT_UPDATE: "student:update",
  STUDENT_DELETE: "student:delete",

  CLASS_STUDENT_CREATE: "class-student:create",
  CLASS_STUDENT_READ: "class-student:read",
  CLASS_STUDENT_DELETE: "class-student:delete",

  STUDENT_CLASS_CREATE: "student-class:create",
  STUDENT_CLASS_READ: "student-class:read",
  STUDENT_CLASS_DELETE: "student-class:delete",

  BULK_IMPORT_EXECUTE: "bulk-import:execute",

  // Evaluation configuration & instruments
  EVALUATION_PERIOD_MANAGE: "evaluation-period:manage",
  EVALUATION_FORM_MANAGE: "evaluation-form:manage",
  EVALUATION_SUBMIT_SET: "evaluation:submit-set",
  EVALUATION_SUBMIT_SEF: "evaluation:submit-sef",

  // Evaluation Report Suite (IFER & FEDAF - CHED Memo 19 s2025)
  EVALUATION_REPORT_GENERATE: "evaluation-report:generate",
  EVALUATION_REPORT_VIEW_SELF: "evaluation-report:view-self",
  EVALUATION_REPORT_VIEW_ALL: "evaluation-report:view-all",
  EVALUATION_REPORT_MANAGE_STATUS: "evaluation-report:manage-status",

  // Account Management
  ACCOUNT_CREATE: "account:create",
  ACCOUNT_READ: "account:read",
  ACCOUNT_UPDATE: "account:update",
  ACCOUNT_DELETE: "account:delete",
  ACCOUNT_UPDATE_OWN: "account:update-own",
  ACCOUNT_MANAGE_ROLES: "account:manage-roles",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ROLE_PERMISSION_MATRIX: Record<RoleName, Permission[]> = {
  [SYSTEM_ROLES.SYS_ADMIN]: Object.values(PERMISSIONS),

  [SYSTEM_ROLES.ADMIN]: [
    // Institutional Records (No top-level deletes)
    PERMISSIONS.COLLEGE_CREATE,
    PERMISSIONS.COLLEGE_READ,
    PERMISSIONS.COLLEGE_UPDATE,

    PERMISSIONS.PROGRAM_CREATE,
    PERMISSIONS.PROGRAM_READ,
    PERMISSIONS.PROGRAM_UPDATE,
    PERMISSIONS.PROGRAM_DELETE,

    PERMISSIONS.COURSE_CREATE,
    PERMISSIONS.COURSE_READ,
    PERMISSIONS.COURSE_UPDATE,
    PERMISSIONS.COURSE_DELETE,

    PERMISSIONS.COURSE_CURRICULUM_CREATE,
    PERMISSIONS.COURSE_CURRICULUM_READ,
    PERMISSIONS.COURSE_CURRICULUM_UPDATE,
    PERMISSIONS.COURSE_CURRICULUM_DELETE,

    PERMISSIONS.SEMESTER_CREATE,
    PERMISSIONS.SEMESTER_READ,
    PERMISSIONS.SEMESTER_UPDATE,

    PERMISSIONS.COURSE_OFFERING_CREATE,
    PERMISSIONS.COURSE_OFFERING_READ,
    PERMISSIONS.COURSE_OFFERING_UPDATE,
    PERMISSIONS.COURSE_OFFERING_DELETE,

    PERMISSIONS.CLASS_CREATE,
    PERMISSIONS.CLASS_READ,
    PERMISSIONS.CLASS_UPDATE,
    PERMISSIONS.CLASS_DELETE,

    // Rosters & Imports
    PERMISSIONS.FACULTY_CREATE,
    PERMISSIONS.FACULTY_READ,
    PERMISSIONS.FACULTY_UPDATE,
    PERMISSIONS.FACULTY_DELETE,

    PERMISSIONS.STUDENT_CREATE,
    PERMISSIONS.STUDENT_READ,
    PERMISSIONS.STUDENT_UPDATE,
    PERMISSIONS.STUDENT_DELETE,

    PERMISSIONS.CLASS_STUDENT_CREATE,
    PERMISSIONS.CLASS_STUDENT_READ,
    PERMISSIONS.CLASS_STUDENT_DELETE,

    PERMISSIONS.STUDENT_CLASS_CREATE,
    PERMISSIONS.STUDENT_CLASS_READ,
    PERMISSIONS.STUDENT_CLASS_DELETE,

    PERMISSIONS.BULK_IMPORT_EXECUTE,

    // Evaluations (Unchanged for Admin)
    PERMISSIONS.EVALUATION_PERIOD_MANAGE,
    PERMISSIONS.EVALUATION_FORM_MANAGE, // <-- Kept for full form & question management
    PERMISSIONS.EVALUATION_REPORT_GENERATE,
    PERMISSIONS.EVALUATION_REPORT_VIEW_ALL,
    PERMISSIONS.EVALUATION_REPORT_MANAGE_STATUS,

    // User Directory (No role delegation or account hard-deletes)
    PERMISSIONS.ACCOUNT_CREATE,
    PERMISSIONS.ACCOUNT_READ,
    PERMISSIONS.ACCOUNT_UPDATE,
    PERMISSIONS.ACCOUNT_UPDATE_OWN,
  ],

  [SYSTEM_ROLES.SUPERVISOR]: [
    PERMISSIONS.PROGRAM_READ,
    PERMISSIONS.COURSE_READ,
    PERMISSIONS.COURSE_CURRICULUM_READ,
    PERMISSIONS.SEMESTER_READ,
    PERMISSIONS.CLASS_READ,
    PERMISSIONS.FACULTY_READ,
    PERMISSIONS.STUDENT_READ,
    PERMISSIONS.CLASS_STUDENT_READ,
    PERMISSIONS.STUDENT_CLASS_READ,
    PERMISSIONS.EVALUATION_SUBMIT_SEF,
    PERMISSIONS.EVALUATION_REPORT_VIEW_ALL,
    PERMISSIONS.EVALUATION_REPORT_MANAGE_STATUS,
    PERMISSIONS.ACCOUNT_UPDATE_OWN,
  ],

  [SYSTEM_ROLES.FACULTY]: [
    PERMISSIONS.CLASS_READ,
    PERMISSIONS.CLASS_STUDENT_READ,
    PERMISSIONS.STUDENT_CLASS_READ,
    PERMISSIONS.EVALUATION_REPORT_VIEW_SELF,
    PERMISSIONS.ACCOUNT_UPDATE_OWN,
  ],

  [SYSTEM_ROLES.STUDENT]: [
    PERMISSIONS.CLASS_READ,
    PERMISSIONS.CLASS_STUDENT_READ,
    PERMISSIONS.STUDENT_CLASS_READ,
    PERMISSIONS.EVALUATION_SUBMIT_SET,
    PERMISSIONS.ACCOUNT_UPDATE_OWN,
  ],
};
